name: Tests

on:
  push:
    branches-ignore:
      - auto-backport-of-pr-[0-9]+
      - v[0-9]+.[0-9]+.[0-9x]+-doc
  pull_request:

env:
  NO_AT_BRIDGE: 1  # Necessary for GTK3 interactive test.
  OPENBLAS_NUM_THREADS: 1
  PYTHONFAULTHANDLER: 1

jobs:
  test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }} ${{ matrix.name-suffix }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name-suffix: "(Minimum Versions)"
            os: ubuntu-18.04
            python-version: 3.7
            extra-requirements: '-c requirements/testing/minver.txt'
            pyqt5-ver: '==5.8 sip==4.19.7'  # oldest versions with a Py3.7 wheel.
            delete-font-cache: true
            XVFB_RUN: xvfb-run -a
          - os: ubuntu-18.04
            python-version: 3.7
            extra-requirements: '-r requirements/testing/extra.txt'
            XVFB_RUN: xvfb-run -a
            CFLAGS: "-fno-lto"  # Ensure that disabling LTO works.
          - os: ubuntu-18.04
            python-version: 3.8
            extra-requirements: '-r requirements/testing/extra.txt'
            XVFB_RUN: xvfb-run -a
          - os: ubuntu-20.04
            python-version: 3.9
            extra-requirements: '-r requirements/testing/extra.txt'
            XVFB_RUN: xvfb-run -a
          - os: ubuntu-20.04
            python-version: '3.10-dev'
            # Re-add this when extra dependencies have wheels.
            # extra-requirements: '-r requirements/testing/extra.txt'
            XVFB_RUN: xvfb-run -a
          - os: macos-latest
            python-version: 3.8
            XVFB_RUN: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OS dependencies
        run: |
          case "${{ runner.os }}" in
          Linux)
            sudo apt-get update -yy
            sudo apt-get install -yy \
              ccache \
              cm-super \
              dvipng \
              ffmpeg \
              fonts-noto-cjk \
              gdb \
              gir1.2-gtk-3.0 \
              graphviz \
              inkscape \
              lcov \
              libcairo2 \
              libcairo2-dev \
              libffi-dev \
              libgeos-dev \
              libgirepository1.0-dev \
              libsdl2-2.0-0 \
              libxkbcommon-x11-0 \
              libxcb-icccm4 \
              libxcb-image0 \
              libxcb-keysyms1 \
              libxcb-randr0 \
              libxcb-render-util0 \
              libxcb-xinerama0 \
              lmodern \
              fonts-freefont-otf \
              texlive-pictures \
              pkg-config \
              qtbase5-dev \
              texlive-fonts-recommended \
              texlive-latex-base \
              texlive-latex-extra \
              texlive-latex-recommended \
              texlive-luatex \
              texlive-xetex \
              ttf-wqy-zenhei
            if [[ "${{ matrix.os }}" = ubuntu-20.04 ]]; then
              sudo apt install -yy libopengl0
            fi
            ;;
          macOS)
            brew install ccache
            brew tap homebrew/cask-fonts
            brew install font-noto-sans-cjk-sc
            ;;
          esac

      - name: Cache pip
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('requirements/*/*.txt') }}
          restore-keys: |
            ${{ matrix.os }}-py${{ matrix.python-version }}-pip-
      - name: Cache pip
        uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ matrix.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('requirements/*/*.txt') }}
          restore-keys: |
            ${{ matrix.os }}-py${{ matrix.python-version }}-pip-
      - name: Cache ccache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
          key: ${{ matrix.os }}-py${{ matrix.python-version }}-ccache-${{ hashFiles('src/*') }}
          restore-keys: |
            ${{ matrix.os }}-py${{ matrix.python-version }}-ccache-
      - name: Cache Matplotlib
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/matplotlib
            !~/.cache/matplotlib/tex.cache
            !~/.cache/matplotlib/test_cache
          key: 1-${{ runner.os }}-py${{ matrix.python-version }}-mpl-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            1-${{ runner.os }}-py${{ matrix.python-version }}-mpl-${{ github.ref }}-
            1-${{ runner.os }}-py${{ matrix.python-version }}-mpl-

      - name: Install Python dependencies
        run: |
          # Upgrade pip and setuptools and wheel to get as clean an install as
          # possible.
          python -m pip install --upgrade pip setuptools wheel

          # Install dependencies from PyPI.
          python -m pip install --upgrade $PRE \
            cycler fonttools kiwisolver numpy packaging pillow pyparsing \
            python-dateutil setuptools-scm \
            -r requirements/testing/all.txt \
            ${{ matrix.extra-requirements }}

          # Install optional dependencies from PyPI.
          # Sphinx is needed to run sphinxext tests
          python -m pip install --upgrade sphinx

          # GUI toolkits are pip-installable only for some versions of Python
          # so don't fail if we can't install them.  Make it easier to check
          # whether the install was successful by trying to import the toolkit
          # (sometimes, the install appears to be successful but shared
          # libraries cannot be loaded at runtime, so an actual import is a
          # better check).
          # PyGObject, pycairo, and cariocffi do not install on OSX 10.12.
           python -m pip install --upgrade pycairo 'cairocffi>=0.8' PyGObject &&
             python -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import Gtk' &&
             echo 'PyGObject is available' ||
             echo 'PyGObject is not available'

          # There are no functioning wheels available for OSX 10.12 (as of
          # Sept 2020) for either pyqt5 (there are only wheels for 10.13+) or
          # pyside2 (the latest version (5.13.2) with 10.12 wheels has a
          # fatal to us bug, it was fixed in 5.14.0 which has 10.13 wheels)
          python -mpip install --upgrade pyqt5${{ matrix.pyqt5-ver }} &&
            python -c 'import PyQt5.QtCore' &&
            echo 'PyQt5 is available' ||
            echo 'PyQt5 is not available'
          if [[ "${{ runner.os }}" != 'macOS' ]]; then
            python -mpip install --upgrade pyside2 &&
              python -c 'import PySide2.QtCore' &&
              echo 'PySide2 is available' ||
              echo 'PySide2 is not available'
          fi
          # Qt6 crashes on Github's ubuntu 18.04 runner.
          if [[ "${{ matrix.os }}" = ubuntu-20.04 ]]; then
            python -mpip install --upgrade pyqt6 &&
              python -c 'import PyQt6.QtCore' &&
              echo 'PyQt6 is available' ||
              echo 'PyQt6 is not available'
            python -mpip install --upgrade pyside6 &&
              python -c 'import PySide6.QtCore' &&
              echo 'PySide6 is available' ||
              echo 'PySide6 is not available'
          fi

          python -mpip install --upgrade \
            -f "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/${{ matrix.os }}" \
            wxPython &&
            python -c 'import wx' &&
            echo 'wxPython is available' ||
            echo 'wxPython is not available'

      - name: Install Matplotlib
        run: |
          ccache -s
          git describe

          # Set flag in a delayed manner to avoid issues with installing other
          # packages
          if [[ "${{ runner.os }}" != 'macOS' ]]; then
            if [[ "$(lsb_release -r -s)" == "20.04" ]]; then
              export CPPFLAGS='--coverage -fprofile-abs-path'
            else
              export CPPFLAGS='--coverage'
            fi
          fi

          # All dependencies must have been pre-installed, so that the minver
          # constraints are held.
          python -m pip install --no-deps -e .

          if [[ "${{ runner.os }}" != 'macOS' ]]; then
            unset CPPFLAGS
          fi

      - name: Clear font cache
        run: |
          rm -rf ~/.cache/matplotlib
        if: matrix.delete-font-cache

      - name: Run pytest
        run: |
          ${{ matrix.XVFB_RUN }} python -mpytest -raR -n auto \
            --maxfail=50 --timeout=300 --durations=25 \
            --cov-report=xml --cov=lib --log-level=DEBUG

  test-cygwin:
    runs-on: windows-latest
    name: Python 3.9 on Cygwin
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    env:
      SHELLOPTS: igncr
      CYGWIN_NOWINPATH: 1
      CHERE_INVOKING: 1

    steps:
      - name: Fix line endings
        run: git config --global core.autocrlf input

      - uses: cygwin/cygwin-install-action@v2
        with:
          packages: >-
            ccache gcc-g++ gdb graphviz libcairo-devel libffi-devel libgeos-devel libQt5Core-devel pkgconf
            texlive-collection-pictures texlive-collection-fontsrecommended texlive-collection-latex
            texlive-collection-latexextra texlive-collection-latexrecommended texlive-collection-luatex
            texlive-collection-xetex noto-cjk-fonts
            python39-devel
            python39-pip
            python39-wheel
            python39-setuptools
            python39-cycler
            python39-dateutil
            python39-fonttools
            python39-imaging
            python39-kiwisolver
            python39-numpy
            python39-packaging
            python39-pyparsing
            python39-sphinx
            python-cairo-devel
            python39-cairo
            python39-gi
            python39-wx
            xorg-server-extra libxcb-icccm4 libxcb-image0 libxcb-keysyms1
            libxcb-randr0 libxcb-render-util0 libxcb-xinerama0
            make autoconf autoconf2.5 automake automake1.14 libtool
            libjpeg-devel libwebp-devel

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: C:\cygwin\home\runneradmin\.cache\pip
          key: Cygwin-py3.9-pip-${{ hashFiles('requirements/*/*.txt') }}
          restore-keys: |
            Cygwin-py3.9-pip-

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: C:\cygwin\home\runneradmin\.ccache
          key: Cygwin-py3.9-ccache-${{ hashFiles('src/*') }}
          restore-keys: Cygwin-py3.9-ccache-

      - name: Cache Matplotlib
        uses: actions/cache@v3
        with:
          path: |
            C:\cygwin\home\runneradmin/.cache/matplotlib
            !C:\cygwin\home\runneradmin/.cache/matplotlib/tex.cache
            !C:\cygwin\home\runneradmin/.cache/matplotlib/test_cache
          key: 1-Cygwin-py3.9-mpl-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            1-Cygwin-py3.9-mpl-${{ github.ref }}-
            1-Cygwin-py3.9-mpl-

      - name: Ensure correct python version
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          /usr/sbin/alternatives --set python /usr/bin/python3.9
          /usr/sbin/alternatives --set python3 /usr/bin/python3.9

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check missing files
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          ls -l /usr/include/python*/Python.h
          file /usr/include/python*/Python.h

      - name: Install Python dependencies
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          python -m pip install --upgrade pip 'setuptools<60' wheel
          python -m pip install kiwisolver 'numpy!=1.21.*' pillow
          grep -v -F -e psutil requirements/testing/all.txt >requirements_test.txt
          python -m pip install --upgrade cycler fonttools kiwisolver numpy packaging pillow pyparsing \
              python-dateutil setuptools-scm -r requirements_test.txt sphinx
          python -m pip install --upgrade pycairo 'cairocffi>=0.8' PyGObject &&
             python -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import Gtk' &&
             echo 'PyGObject is available' ||
             echo 'PyGObject is not available'
          python -m pip install --upgrade pyqt5  &&
             python -c 'import PyQt5.QtCore' &&
             echo 'PyQt5 is available' ||
             echo 'PyQt5 is not available'
          python -mpip install --upgrade pyside2 &&
              python -c 'import PySide2.QtCore' &&
              echo 'PySide2 is available' ||
              echo 'PySide2 is not available'
          python -m pip install --upgrade wxPython  &&
            python -c 'import wx' &&
            echo 'wxPython is available' ||
            echo 'wxPython is not available'

      - name: Install matplotlib
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          ccache -s
          git describe
          # Set flag in a delayed manner to avoid issues with installing other
          # packages
          export CPPFLAGS='--coverage'
          cat <<EOT >> mplsetup.cfg
          [rc_options]
          backend=Agg

          [libs]
          system_freetype = False
          system_qhull = False
          EOT
          cat mplsetup.cfg
          python setup.py build_ext
          # All dependencies must have been pre-installed, so that the minver
          # constraints are held.
          python -m pip install --no-deps -ve .
          unset CPPFLAGS

      - name: Rebase DLLs
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          /usr/bin/rebase --database $(find {/usr,/usr/local/,~,~/.local}/{bin,lib/python3.?/site-packages} -name \*.exe -o -name \*.dll)

      - name: Run pytest
        shell: bash.exe -eo pipefail -o igncr "{0}"
        run: |
          xvfb-run -a python -mpytest -raR -n auto \
            --maxfail=50 --timeout=300 --durations=25 \
            --cov-report=xml --cov=lib --log-level=DEBUG --color=yes

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: "3.9 Cygwin result images"
          path: ./result_images

      - name: Filter C coverage
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --output-file coverage.info \
            --extract coverage.info $PWD/src/'*' $PWD/lib/'*'
          lcov --list coverage.info
          find . -name '*.gc*' -delete

      - name: Upload code coverage
        uses: codecov/codecov-action@v2

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: "3.9 Cygwin result images"
          path: ./result_images
